GRAPHRAG_LLM_MODEL: gpt-4o
GRAPHRAG_LLM_API_BASE: null
GRAPHRAG_EMBEDDING_MODEL: text-embedding-3-small
GRAPHRAG_EMBEDDING_API_BASE: null
GRAPHRAG_CLAIM_EXTRACTION_ENABLED: False
INPUT_DIR: "./artifacts"
COMMUNITY_LEVEL: 2